### ISSUE TITLE
[Suggestion] Add view players logs with a command

### ISSUE THREAD

**Issue by PixelmonPRO** [ModdedMinecraft/MMCLogger-Sponge#4]
Hello! I have been using this plugin for a long time, and it would be very convenient to be able to view player logs through the command.
Example: /mmclogger view player - after command, plugin loads the player log to `gist`, or `hastebin`and gives a link to it.

**Comment by leelawd** [comment]
Ok, so i kind of got this implemented in some way, i was wondering if this would be suitable for yourself or you would also prefer there to be a single command to look up the specific player

![chatlogs](https://user-images.githubusercontent.com/3026728/54865298-5aaa8c80-4d5b-11e9-86c8-a39575e08da3.gif)

**Comment by leelawd** [comment]
Also added /vcl (player) to get a specific players file quickly

It is now on Ore, v 1.7.0

**Comment by PixelmonPRO** [comment]
@leelawd Thank you for update ^^
Works, but large player log have error:
https://gist.github.com/PixelmonPRO/b9719ba4249b05ec8705f27dc16d276c
And example, RU characters in chat no display correct:
https://hastebin.com/urazogisen

**Comment by leelawd** [comment]
https://ore.spongepowered.org/leelawd93/MMCLogger/versions/1.7.1

Would you mind trying with the latest update?

**Comment by PixelmonPRO** [comment]
@leelawd RU characters: https://hastebin.com/qicumobubu

**Comment by leelawd** [comment]
https://ore.spongepowered.org/leelawd93/MMCLogger/versions/1.7.2

Swap the config to use ISO-8859-1 instead of UTF-8 then either restart or "/sponge plugins reload" and this should be fixed.
