### ISSUE TITLE
File write issue

### ISSUE THREAD

**Issue by ghost** [ModdedMinecraft/MMCLogger-Sponge#5]
When you restart the server, it wipes the data in all the logs. My guess is that you don't have it append the log file if it already exists.

**Comment by leelawd** [comment]
I have not noticed this behaviour on on any of the 4 servers i develop on or even my test setup, is there any other information you could provide?

**Comment by ghost** [comment]
I am using spongeforge-1.12.2-2768-7.1.5.jar & the latest release from your releases tab.

**Comment by leelawd** [comment]
https://ore.spongepowered.org/leelawd93/MMCLogger/versions

Try from here

**Comment by ghost** [comment]
Thanks, using that version fixed it for me.
